SEED_VERSION = "v1.3.0"

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.1:8b"

MEMORY_SEARCH_LIMIT = 8
IMPORTANT_MEMORY_LIMIT = 5
RECENT_MEMORY_LIMIT = 5

RECENT_JOURNAL_LIMIT = 5
SESSION_HISTORY_LIMIT = 8

AUTOSUGGEST_DEFAULT = True

SEED_MODE = "local terminal"
LLM_STATUS = "connected through local Ollama when Ollama is running"

CHAT_LOG_DIR = "seed_logs"
CHAT_LOG_TAIL_LINES = 40
LOG_COMMAND_EVENTS = True

SUMMARY_MAX_LOG_LINES = 120
SUMMARY_MEMORY_TYPE = "technical_progress"
SUMMARY_IMPORTANCE = 5

PROJECT_ROOT = "."
PROJECT_REPORT_MEMORY_TYPE = "technical_progress"
PROJECT_REPORT_IMPORTANCE = 5

PROJECT_IGNORED_FOLDERS = [
    "__pycache__",
    ".git",
    "seed_logs"
]

PROJECT_IGNORED_FILES = [
    ".DS_Store"
]

PROJECT_CONTEXT_ENABLED = True
PROJECT_CONTEXT_FILE_LIMIT = 40

MEMORY_DEBUG_LIMIT = 12
MEMORY_DIRECT_MATCH_THRESHOLD = 1

VISUAL_THEME_NAME = "Seed Dark Amber"
VISUAL_ACCENT = "orange1"
VISUAL_PANEL_STYLE = "grey23"
VISUAL_SUCCESS_STYLE = "green"
VISUAL_WARNING_STYLE = "yellow"
VISUAL_ERROR_STYLE = "red"